const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const base='http://127.0.0.1:8881';await page.goto(base+'/edit-helper#cooking-audio');
 assert.equal(await page.locator('#hooks').isVisible(),false);
 const video=await(await page.request.get(base+'/_test/video')).body();
 const srt=await(await page.request.get(base+'/_test/srt')).body();
 await page.locator('#ca-file').setInputFiles({name:'clock.mp4',mimeType:'video/mp4',buffer:video});
 await page.locator('#ca-srt').setInputFiles({name:'recipe.srt',mimeType:'text/plain',buffer:srt});
 await page.locator('#ca-create').click();await page.waitForFunction(()=>!document.getElementById('ca-analyze').disabled);
 await page.locator('#ca-analyze').click();await page.locator('#ca-candidates .candidate').waitFor();
 assert.ok((await page.locator('#ca-candidates').innerText()).includes('리액션 포함'));
 await page.locator('#ca-candidates button').filter({hasText:'구간 재생'}).click();
 await page.waitForFunction(()=>document.getElementById('ca-player').readyState>=2);
 await page.locator('#ca-player').evaluate(v=>v.pause());
 await page.locator('#ca-export').click();await page.locator('#ca-results a').filter({hasText:'전체 ZIP'}).waitFor();
 const href=await page.locator('#ca-results a').filter({hasText:'전체 ZIP'}).getAttribute('href');assert.equal((await page.request.get(base+href)).status(),200);
 await page.reload();await page.locator('#ca-results a').filter({hasText:'전체 ZIP'}).waitFor();
 assert.equal(await page.locator('#cooking-audio').isVisible(),true);
 await page.locator('#hooksTool').click();assert.equal(await page.locator('#cooking-audio').isVisible(),false);
 await page.locator('#cookingTool').click();await page.locator('#ca-analyze').click();await page.waitForFunction(()=>document.getElementById('ca-usage').textContent.includes('AI 0회'));
 await page.screenshot({path:'/tmp/cooking-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'/tmp/cooking-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.deepEqual(errors,[]);
 await browser.close();console.log('Cooking browser flow passed: upload, analysis, reaction, preview, MP3/ZIP, reload, tabs, cache, mobile');
})().catch(e=>{console.error(e);process.exit(1);});
